/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v4.1
processor: MKE18F512xxx16
package_id: MKE18F512VLL16
mcu_data: ksdk2_0
processor_version: 4.0.0
pin_labels:
- {pin_num: '4', pin_signal: ADC2_SE0/PTD0/FTM0_CH2/LPSPI1_SCK/FTM2_CH0/FXIO_D0/TRGMUX_OUT1, label: MCU_A0, identifier: MCU_A0}
- {pin_num: '3', pin_signal: ADC2_SE1/PTD1/FTM0_CH3/LPSPI1_SIN/FTM2_CH1/FXIO_D1/TRGMUX_OUT2, label: MCU_A1, identifier: MCU_A1}
- {pin_num: '71', pin_signal: ADC1_SE2/PTD2/FTM3_CH4/LPSPI1_SOUT/FXIO_D4/TRGMUX_IN5, label: MCU_A2, identifier: MCU_A2}
- {pin_num: '70', pin_signal: ADC1_SE3/PTD3/FTM3_CH5/LPSPI1_PCS0/FXIO_D5/TRGMUX_IN4/NMI_b, label: MCU_A3, identifier: MCU_A3}
- {pin_num: '69', pin_signal: ADC1_SE6/ACMP1_IN6/PTD4/FTM0_FLT3/FTM3_FLT3, label: MCU_A4, identifier: MCU_A4}
- {pin_num: '33', pin_signal: PTD5/FTM2_CH3/LPTMR0_ALT2/FTM2_FLT1/PWT_IN2/TRGMUX_IN7, label: MCU_A5, identifier: MCU_A5}
- {pin_num: '32', pin_signal: PTD6/LPUART2_RX/FTM2_FLT2, label: MCU_A6, identifier: MCU_A6}
- {pin_num: '31', pin_signal: PTD7/LPUART2_TX/FTM2_FLT3, label: MCU_A7, identifier: MCU_A7}
- {pin_num: '42', pin_signal: PTD8/LPI2C1_SDA/FTM2_FLT2/FTM1_CH4, label: MCU_A8, identifier: MCU_A8}
- {pin_num: '41', pin_signal: ACMP1_IN5/PTD9/LPI2C1_SCL/FTM2_FLT3/FTM1_CH5, label: MCU_A9, identifier: MCU_A9}
- {pin_num: '36', pin_signal: PTD10/FTM2_CH0/FTM2_QD_PHB, label: MCU_A10, identifier: MCU_A10}
- {pin_num: '35', pin_signal: PTD11/FTM2_CH1/FTM2_QD_PHA/LPUART2_CTS, label: MCU_A11, identifier: MCU_A11}
- {pin_num: '34', pin_signal: PTD12/FTM2_CH2/LPI2C1_HREQ/LPUART2_RTS, label: MCU_A12, identifier: MCU_A12}
- {pin_num: '25', pin_signal: PTD13/FTM2_CH4/RTC_CLKOUT, label: MCU_A13, identifier: MCU_A13}
- {pin_num: '24', pin_signal: PTD14/FTM2_CH5/CLKOUT, label: MCU_A14, identifier: MCU_A14}
- {pin_num: '22', pin_signal: ACMP2_IN1/PTD15/FTM0_CH0, label: MCU_A15, identifier: MCU_A15}
- {pin_num: '21', pin_signal: ACMP2_IN0/PTD16/FTM0_CH1, label: MCU_VMA, identifier: MCU_VMA}
- {pin_num: '20', pin_signal: PTD17/FTM0_FLT2/LPUART2_RX, label: MCU_RW, identifier: MCU_RW}
- {pin_num: '98', pin_signal: PTA4/ACMP0_OUT/EWM_OUT_b/JTAG_TMS/SWD_DIO, label: SWD_DIO}
- {pin_num: '92', pin_signal: PTA10/FTM1_CH4/LPUART0_TX/FXIO_D0/JTAG_TDO/noetm_Trace_SWO, label: SWO}
- {pin_num: '96', pin_signal: ACMP0_IN2/PTC4/FTM1_CH0/RTC_CLKOUT/EWM_IN/FTM1_QD_PHB/JTAG_TCLK/SWD_CLK, label: SWD_CLK}
- {pin_num: '97', pin_signal: PTA5/TCLK1/JTAG_TRST_b/RESET_b, label: NRESET, identifier: NRESET}
- {pin_num: '54', pin_signal: ADC0_SE4/ADC1_SE14/PTB0/LPUART0_RX/LPSPI0_PCS0/LPTMR0_ALT3/PWT_IN3, label: MCU_D0, identifier: MCU_D0}
- {pin_num: '53', pin_signal: ADC0_SE5/ADC1_SE15/PTB1/LPUART0_TX/LPSPI0_SOUT/TCLK0, label: MCU_D1, identifier: MCU_D1}
- {pin_num: '48', pin_signal: ADC0_SE6/PTB2/FTM1_CH0/LPSPI0_SCK/FTM1_QD_PHB/TRGMUX_IN3, label: MCU_D2, identifier: MCU_D2}
- {pin_num: '47', pin_signal: ADC0_SE7/PTB3/FTM1_CH1/LPSPI0_SIN/FTM1_QD_PHA/TRGMUX_IN2, label: MCU_D3, identifier: MCU_D3}
- {pin_num: '28', pin_signal: ACMP1_IN2/PTB4/FTM0_CH4/LPSPI0_SOUT/TRGMUX_IN1, label: MCU_D4, identifier: MCU_D4}
- {pin_num: '27', pin_signal: PTB5/FTM0_CH5/LPSPI0_PCS1/TRGMUX_IN0/ACMP1_OUT, label: MCU_D5, identifier: MCU_D5}
- {pin_num: '16', pin_signal: XTAL/PTB6/LPI2C0_SDA, label: MCU_D6, identifier: MCU_D6}
- {pin_num: '15', pin_signal: EXTAL/PTB7/LPI2C0_SCL, label: MCU_D7, identifier: MCU_D7}
- {pin_num: '79', pin_signal: ADC0_SE0/ACMP0_IN0/PTA0/FTM2_CH1/LPI2C0_SCLS/FXIO_D2/FTM2_QD_PHA/LPUART0_CTS/TRGMUX_OUT3, label: MCU_NMI, identifier: MCU_NMI}
- {pin_num: '58', pin_signal: ADC0_SE2/ACMP1_IN0/PTA6/FTM0_FLT1/LPSPI1_PCS1/LPUART1_CTS, label: MCU_IRQ, identifier: MCU_IRQ}
- {pin_num: '100', pin_signal: PTA8/FXIO_D6/FTM3_FLT3, label: MCU_E, identifier: MCU_E}
- {pin_num: '99', pin_signal: PTA9/FXIO_D7/FTM3_FLT2/FTM1_FLT3, label: MCU_RESET, identifier: MCU_RESET}
- {pin_num: '78', pin_signal: ADC0_SE1/ACMP0_IN1/PTA1/FTM1_CH1/LPI2C0_SDAS/FXIO_D3/FTM1_QD_PHA/LPUART0_RTS/TRGMUX_OUT0, label: UART0_RTS, identifier: UART0_RTS}
- {pin_num: '73', pin_signal: ADC1_SE0/PTA2/FTM3_CH0/LPI2C0_SDA/EWM_OUT_b/LPUART0_RX, label: UART0_RX, identifier: UART0_RX}
- {pin_num: '72', pin_signal: ADC1_SE1/PTA3/FTM3_CH1/LPI2C0_SCL/EWM_IN/LPUART0_TX, label: UART0_TX, identifier: UART0_TX}
- {pin_num: '57', pin_signal: ADC0_SE3/ACMP1_IN1/PTA7/FTM0_FLT2/RTC_CLKIN/LPUART1_RTS, label: UART1_RTS, identifier: UART1_RTS}
- {pin_num: '90', pin_signal: ADC2_SE5/PTA12/FTM1_CH6/CAN1_RX/LPI2C1_SDAS, label: CAN1_RX, identifier: CAN1_RX}
- {pin_num: '89', pin_signal: ADC2_SE4/PTA13/FTM1_CH7/CAN1_TX/LPI2C1_SCLS, label: CAN1_TX, identifier: CAN1_TX}
- {pin_num: '81', pin_signal: ADC1_SE4/PTC6/LPUART1_RX/CAN1_RX/FTM3_CH2, label: UART1_RX, identifier: UART1_RX}
- {pin_num: '80', pin_signal: ADC1_SE5/PTC7/LPUART1_TX/CAN1_TX/FTM3_CH3, label: UART1_TX, identifier: UART1_TX}
- {pin_num: '9', pin_signal: PTE4/BUSOUT/FTM2_QD_PHB/FTM2_CH2/CAN0_RX/FXIO_D6/EWM_OUT_b, label: CAN0_RX, identifier: CAN0_RX}
- {pin_num: '8', pin_signal: PTE5/TCLK2/FTM2_QD_PHA/FTM2_CH3/CAN0_TX/FXIO_D7/EWM_IN, label: CAN0_TX, identifier: CAN0_TX}
- {pin_num: '23', pin_signal: ACMP2_IN2/DAC0_OUT/PTE9/FTM0_CH7/LPUART2_CTS, label: DAC_OUT, identifier: DAC_OUT}
- {pin_num: '66', pin_signal: ADC1_SE9/ADC2_SE9/PTB14/FTM0_CH2/LPSPI1_SCK, label: LED_1, identifier: LED_1}
- {pin_num: '65', pin_signal: ADC1_SE14/PTB15/FTM0_CH3/LPSPI1_SIN, label: LED_2, identifier: LED_2}
- {pin_num: '64', pin_signal: ADC1_SE15/PTB16/FTM0_CH4/LPSPI1_SOUT, label: LED_3, identifier: LED_3}
- {pin_num: '63', pin_signal: ADC2_SE3/PTB17/FTM0_CH5/LPSPI1_PCS3, label: LED_4, identifier: LED_4}
- {pin_num: '40', pin_signal: ADC0_SE8/ACMP1_IN4/PTC0/FTM0_CH0/FTM1_CH6, label: EX_5_E_CLK_OUT, identifier: EX_5}
- {pin_num: '39', pin_signal: ADC0_SE9/ACMP1_IN3/PTC1/FTM0_CH1/FTM1_CH7, label: EX_4, identifier: EX_4}
- {pin_num: '30', pin_signal: ADC0_SE10/ACMP0_IN5/XTAL32/PTC2/FTM0_CH2/CAN0_RX, label: EX_3, identifier: EX_3}
- {pin_num: '29', pin_signal: ADC0_SE11/ACMP0_IN4/EXTAL32/PTC3/FTM0_CH3/CAN0_TX, label: EX_2, identifier: EX_2}
- {pin_num: '45', pin_signal: ADC0_SE13/ACMP2_IN4/PTC15/FTM1_CH3, label: EX_8, identifier: EX_8}
- {pin_num: '44', pin_signal: ADC0_SE14/PTC16/FTM1_FLT2/LPI2C1_SDAS, label: EX_7, identifier: EX_7}
- {pin_num: '43', pin_signal: ADC0_SE15/PTC17/FTM1_FLT3/LPI2C1_SCLS, label: EX_6, identifier: EX_6}
- {pin_num: '26', pin_signal: ACMP0_IN3/PTE8/FTM0_CH6, label: EX_1, identifier: EX_1}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '14', peripheral: SUPPLY, signal: 'VSS, 1', pin_signal: VSS15}
  - {pin_num: '37', peripheral: SUPPLY, signal: 'VSS, 2', pin_signal: VSS38}
  - {pin_num: '38', peripheral: SUPPLY, signal: 'VDD, 1', pin_signal: VDD39}
  - {pin_num: '60', peripheral: SUPPLY, signal: 'VSS, 3', pin_signal: VSS61}
  - {pin_num: '61', peripheral: SUPPLY, signal: 'VDD, 2', pin_signal: VDD62}
  - {pin_num: '86', peripheral: SUPPLY, signal: 'VSS, 4', pin_signal: VSS87}
  - {pin_num: '87', peripheral: SUPPLY, signal: 'VDD, 3', pin_signal: VDD88}
  - {pin_num: '13', peripheral: ADC0, signal: VREFL, pin_signal: VREFL}
  - {pin_num: '12', peripheral: ADC0, signal: VREFH, pin_signal: VREFH}
  - {pin_num: '11', peripheral: SUPPLY, signal: 'VDDA, 0', pin_signal: VDDA}
  - {pin_num: '10', peripheral: SUPPLY, signal: 'VDD, 0', pin_signal: VDD10}
  - {pin_num: '98', peripheral: CoreDebug, signal: SWD_DIO, pin_signal: PTA4/ACMP0_OUT/EWM_OUT_b/JTAG_TMS/SWD_DIO}
  - {pin_num: '92', peripheral: CoreDebug, signal: TRACE_SWO, pin_signal: PTA10/FTM1_CH4/LPUART0_TX/FXIO_D0/JTAG_TDO/noetm_Trace_SWO}
  - {pin_num: '96', peripheral: CoreDebug, signal: SWD_CLK, pin_signal: ACMP0_IN2/PTC4/FTM1_CH0/RTC_CLKOUT/EWM_IN/FTM1_QD_PHB/JTAG_TCLK/SWD_CLK}
  - {pin_num: '97', peripheral: RCM, signal: RESET, pin_signal: PTA5/TCLK1/JTAG_TRST_b/RESET_b}
  - {pin_num: '4', peripheral: GPIOD, signal: 'GPIO, 0', pin_signal: ADC2_SE0/PTD0/FTM0_CH2/LPSPI1_SCK/FTM2_CH0/FXIO_D0/TRGMUX_OUT1, direction: OUTPUT, drive_strength: low}
  - {pin_num: '3', peripheral: GPIOD, signal: 'GPIO, 1', pin_signal: ADC2_SE1/PTD1/FTM0_CH3/LPSPI1_SIN/FTM2_CH1/FXIO_D1/TRGMUX_OUT2, direction: OUTPUT, drive_strength: low}
  - {pin_num: '71', peripheral: GPIOD, signal: 'GPIO, 2', pin_signal: ADC1_SE2/PTD2/FTM3_CH4/LPSPI1_SOUT/FXIO_D4/TRGMUX_IN5, direction: OUTPUT}
  - {pin_num: '70', peripheral: GPIOD, signal: 'GPIO, 3', pin_signal: ADC1_SE3/PTD3/FTM3_CH5/LPSPI1_PCS0/FXIO_D5/TRGMUX_IN4/NMI_b, direction: OUTPUT, pull_select: down}
  - {pin_num: '69', peripheral: GPIOD, signal: 'GPIO, 4', pin_signal: ADC1_SE6/ACMP1_IN6/PTD4/FTM0_FLT3/FTM3_FLT3, direction: OUTPUT}
  - {pin_num: '33', peripheral: GPIOD, signal: 'GPIO, 5', pin_signal: PTD5/FTM2_CH3/LPTMR0_ALT2/FTM2_FLT1/PWT_IN2/TRGMUX_IN7, direction: OUTPUT}
  - {pin_num: '32', peripheral: GPIOD, signal: 'GPIO, 6', pin_signal: PTD6/LPUART2_RX/FTM2_FLT2, direction: OUTPUT}
  - {pin_num: '31', peripheral: GPIOD, signal: 'GPIO, 7', pin_signal: PTD7/LPUART2_TX/FTM2_FLT3, direction: OUTPUT}
  - {pin_num: '42', peripheral: GPIOD, signal: 'GPIO, 8', pin_signal: PTD8/LPI2C1_SDA/FTM2_FLT2/FTM1_CH4, direction: OUTPUT}
  - {pin_num: '41', peripheral: GPIOD, signal: 'GPIO, 9', pin_signal: ACMP1_IN5/PTD9/LPI2C1_SCL/FTM2_FLT3/FTM1_CH5, direction: OUTPUT}
  - {pin_num: '36', peripheral: GPIOD, signal: 'GPIO, 10', pin_signal: PTD10/FTM2_CH0/FTM2_QD_PHB, direction: OUTPUT}
  - {pin_num: '35', peripheral: GPIOD, signal: 'GPIO, 11', pin_signal: PTD11/FTM2_CH1/FTM2_QD_PHA/LPUART2_CTS, direction: OUTPUT}
  - {pin_num: '34', peripheral: GPIOD, signal: 'GPIO, 12', pin_signal: PTD12/FTM2_CH2/LPI2C1_HREQ/LPUART2_RTS, direction: OUTPUT}
  - {pin_num: '25', peripheral: GPIOD, signal: 'GPIO, 13', pin_signal: PTD13/FTM2_CH4/RTC_CLKOUT, direction: OUTPUT}
  - {pin_num: '24', peripheral: GPIOD, signal: 'GPIO, 14', pin_signal: PTD14/FTM2_CH5/CLKOUT, direction: OUTPUT}
  - {pin_num: '22', peripheral: GPIOD, signal: 'GPIO, 15', pin_signal: ACMP2_IN1/PTD15/FTM0_CH0, direction: OUTPUT}
  - {pin_num: '21', peripheral: GPIOD, signal: 'GPIO, 16', pin_signal: ACMP2_IN0/PTD16/FTM0_CH1, direction: OUTPUT}
  - {pin_num: '20', peripheral: GPIOD, signal: 'GPIO, 17', pin_signal: PTD17/FTM0_FLT2/LPUART2_RX, direction: OUTPUT}
  - {pin_num: '73', peripheral: LPUART0, signal: RX, pin_signal: ADC1_SE0/PTA2/FTM3_CH0/LPI2C0_SDA/EWM_OUT_b/LPUART0_RX}
  - {pin_num: '72', peripheral: LPUART0, signal: TX, pin_signal: ADC1_SE1/PTA3/FTM3_CH1/LPI2C0_SCL/EWM_IN/LPUART0_TX}
  - {pin_num: '90', peripheral: CAN1, signal: RX, pin_signal: ADC2_SE5/PTA12/FTM1_CH6/CAN1_RX/LPI2C1_SDAS}
  - {pin_num: '89', peripheral: CAN1, signal: TX, pin_signal: ADC2_SE4/PTA13/FTM1_CH7/CAN1_TX/LPI2C1_SCLS}
  - {pin_num: '81', peripheral: LPUART1, signal: RX, pin_signal: ADC1_SE4/PTC6/LPUART1_RX/CAN1_RX/FTM3_CH2}
  - {pin_num: '80', peripheral: LPUART1, signal: TX, pin_signal: ADC1_SE5/PTC7/LPUART1_TX/CAN1_TX/FTM3_CH3}
  - {pin_num: '78', peripheral: LPUART0, signal: RTS, pin_signal: ADC0_SE1/ACMP0_IN1/PTA1/FTM1_CH1/LPI2C0_SDAS/FXIO_D3/FTM1_QD_PHA/LPUART0_RTS/TRGMUX_OUT0}
  - {pin_num: '57', peripheral: LPUART1, signal: RTS, pin_signal: ADC0_SE3/ACMP1_IN1/PTA7/FTM0_FLT2/RTC_CLKIN/LPUART1_RTS}
  - {pin_num: '23', peripheral: DAC0, signal: OUT, pin_signal: ACMP2_IN2/DAC0_OUT/PTE9/FTM0_CH7/LPUART2_CTS}
  - {pin_num: '9', peripheral: CAN0, signal: RX, pin_signal: PTE4/BUSOUT/FTM2_QD_PHB/FTM2_CH2/CAN0_RX/FXIO_D6/EWM_OUT_b}
  - {pin_num: '8', peripheral: CAN0, signal: TX, pin_signal: PTE5/TCLK2/FTM2_QD_PHA/FTM2_CH3/CAN0_TX/FXIO_D7/EWM_IN}
  - {pin_num: '54', peripheral: GPIOB, signal: 'GPIO, 0', pin_signal: ADC0_SE4/ADC1_SE14/PTB0/LPUART0_RX/LPSPI0_PCS0/LPTMR0_ALT3/PWT_IN3, direction: INPUT}
  - {pin_num: '53', peripheral: GPIOB, signal: 'GPIO, 1', pin_signal: ADC0_SE5/ADC1_SE15/PTB1/LPUART0_TX/LPSPI0_SOUT/TCLK0, direction: INPUT}
  - {pin_num: '48', peripheral: GPIOB, signal: 'GPIO, 2', pin_signal: ADC0_SE6/PTB2/FTM1_CH0/LPSPI0_SCK/FTM1_QD_PHB/TRGMUX_IN3, direction: INPUT}
  - {pin_num: '47', peripheral: GPIOB, signal: 'GPIO, 3', pin_signal: ADC0_SE7/PTB3/FTM1_CH1/LPSPI0_SIN/FTM1_QD_PHA/TRGMUX_IN2, direction: INPUT}
  - {pin_num: '28', peripheral: GPIOB, signal: 'GPIO, 4', pin_signal: ACMP1_IN2/PTB4/FTM0_CH4/LPSPI0_SOUT/TRGMUX_IN1, direction: INPUT}
  - {pin_num: '27', peripheral: GPIOB, signal: 'GPIO, 5', pin_signal: PTB5/FTM0_CH5/LPSPI0_PCS1/TRGMUX_IN0/ACMP1_OUT, direction: INPUT}
  - {pin_num: '16', peripheral: GPIOB, signal: 'GPIO, 6', pin_signal: XTAL/PTB6/LPI2C0_SDA, direction: INPUT}
  - {pin_num: '15', peripheral: GPIOB, signal: 'GPIO, 7', pin_signal: EXTAL/PTB7/LPI2C0_SCL, direction: INPUT}
  - {pin_num: '79', peripheral: GPIOA, signal: 'GPIO, 0', pin_signal: ADC0_SE0/ACMP0_IN0/PTA0/FTM2_CH1/LPI2C0_SCLS/FXIO_D2/FTM2_QD_PHA/LPUART0_CTS/TRGMUX_OUT3, direction: INPUT,
    gpio_interrupt: kPORT_InterruptFallingEdge}
  - {pin_num: '58', peripheral: GPIOA, signal: 'GPIO, 6', pin_signal: ADC0_SE2/ACMP1_IN0/PTA6/FTM0_FLT1/LPSPI1_PCS1/LPUART1_CTS, direction: INPUT, gpio_interrupt: kPORT_InterruptFallingEdge}
  - {pin_num: '99', peripheral: GPIOA, signal: 'GPIO, 9', pin_signal: PTA9/FXIO_D7/FTM3_FLT2/FTM1_FLT3, direction: INPUT}
  - {pin_num: '66', peripheral: GPIOB, signal: 'GPIO, 14', pin_signal: ADC1_SE9/ADC2_SE9/PTB14/FTM0_CH2/LPSPI1_SCK, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '65', peripheral: GPIOB, signal: 'GPIO, 15', pin_signal: ADC1_SE14/PTB15/FTM0_CH3/LPSPI1_SIN, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '63', peripheral: GPIOB, signal: 'GPIO, 17', pin_signal: ADC2_SE3/PTB17/FTM0_CH5/LPSPI1_PCS3, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '64', peripheral: GPIOB, signal: 'GPIO, 16', pin_signal: ADC1_SE15/PTB16/FTM0_CH4/LPSPI1_SOUT, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '39', peripheral: GPIOC, signal: 'GPIO, 1', pin_signal: ADC0_SE9/ACMP1_IN3/PTC1/FTM0_CH1/FTM1_CH7, direction: OUTPUT}
  - {pin_num: '30', peripheral: GPIOC, signal: 'GPIO, 2', pin_signal: ADC0_SE10/ACMP0_IN5/XTAL32/PTC2/FTM0_CH2/CAN0_RX, direction: OUTPUT}
  - {pin_num: '29', peripheral: GPIOC, signal: 'GPIO, 3', pin_signal: ADC0_SE11/ACMP0_IN4/EXTAL32/PTC3/FTM0_CH3/CAN0_TX, direction: OUTPUT}
  - {pin_num: '45', peripheral: GPIOC, signal: 'GPIO, 15', pin_signal: ADC0_SE13/ACMP2_IN4/PTC15/FTM1_CH3, direction: OUTPUT}
  - {pin_num: '44', peripheral: GPIOC, signal: 'GPIO, 16', pin_signal: ADC0_SE14/PTC16/FTM1_FLT2/LPI2C1_SDAS, direction: OUTPUT}
  - {pin_num: '43', peripheral: GPIOC, signal: 'GPIO, 17', pin_signal: ADC0_SE15/PTC17/FTM1_FLT3/LPI2C1_SCLS, direction: OUTPUT}
  - {pin_num: '26', peripheral: GPIOE, signal: 'GPIO, 8', pin_signal: ACMP0_IN3/PTE8/FTM0_CH6, direction: OUTPUT}
  - {pin_num: '100', peripheral: GPIOA, signal: 'GPIO, 8', pin_signal: PTA8/FXIO_D6/FTM3_FLT3, direction: INPUT}
  - {pin_num: '40', peripheral: FTM0, signal: 'CH, 0', pin_signal: ADC0_SE8/ACMP1_IN4/PTC0/FTM0_CH0/FTM1_CH6, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Clock Control: 0x01u */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Clock Control: 0x01u */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Clock Control: 0x01u */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Clock Control: 0x01u */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Clock Control: 0x01u */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t MCU_NMI_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA0 (pin 79)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_NMI_GPIO, BOARD_INITPINS_MCU_NMI_PIN, &MCU_NMI_config);

    gpio_pin_config_t MCU_IRQ_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA6 (pin 58)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_IRQ_GPIO, BOARD_INITPINS_MCU_IRQ_PIN, &MCU_IRQ_config);

    gpio_pin_config_t MCU_E_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA8 (pin 100)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_E_GPIO, BOARD_INITPINS_MCU_E_PIN, &MCU_E_config);

    gpio_pin_config_t MCU_RESET_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA9 (pin 99)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_RESET_GPIO, BOARD_INITPINS_MCU_RESET_PIN, &MCU_RESET_config);

    gpio_pin_config_t MCU_D0_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB0 (pin 54)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_D0_GPIO, BOARD_INITPINS_MCU_D0_PIN, &MCU_D0_config);

    gpio_pin_config_t MCU_D1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB1 (pin 53)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_D1_GPIO, BOARD_INITPINS_MCU_D1_PIN, &MCU_D1_config);

    gpio_pin_config_t MCU_D2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB2 (pin 48)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_D2_GPIO, BOARD_INITPINS_MCU_D2_PIN, &MCU_D2_config);

    gpio_pin_config_t MCU_D3_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB3 (pin 47)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_D3_GPIO, BOARD_INITPINS_MCU_D3_PIN, &MCU_D3_config);

    gpio_pin_config_t MCU_D4_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB4 (pin 28)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_D4_GPIO, BOARD_INITPINS_MCU_D4_PIN, &MCU_D4_config);

    gpio_pin_config_t MCU_D5_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB5 (pin 27)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_D5_GPIO, BOARD_INITPINS_MCU_D5_PIN, &MCU_D5_config);

    gpio_pin_config_t MCU_D6_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB6 (pin 16)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_D6_GPIO, BOARD_INITPINS_MCU_D6_PIN, &MCU_D6_config);

    gpio_pin_config_t MCU_D7_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB7 (pin 15)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_D7_GPIO, BOARD_INITPINS_MCU_D7_PIN, &MCU_D7_config);

    gpio_pin_config_t LED_1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB14 (pin 66)  */
    GPIO_PinInit(BOARD_INITPINS_LED_1_GPIO, BOARD_INITPINS_LED_1_PIN, &LED_1_config);

    gpio_pin_config_t LED_2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB15 (pin 65)  */
    GPIO_PinInit(BOARD_INITPINS_LED_2_GPIO, BOARD_INITPINS_LED_2_PIN, &LED_2_config);

    gpio_pin_config_t LED_3_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB16 (pin 64)  */
    GPIO_PinInit(BOARD_INITPINS_LED_3_GPIO, BOARD_INITPINS_LED_3_PIN, &LED_3_config);

    gpio_pin_config_t LED_4_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB17 (pin 63)  */
    GPIO_PinInit(BOARD_INITPINS_LED_4_GPIO, BOARD_INITPINS_LED_4_PIN, &LED_4_config);

    gpio_pin_config_t EX_4_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC1 (pin 39)  */
    GPIO_PinInit(BOARD_INITPINS_EX_4_GPIO, BOARD_INITPINS_EX_4_PIN, &EX_4_config);

    gpio_pin_config_t EX_3_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC2 (pin 30)  */
    GPIO_PinInit(BOARD_INITPINS_EX_3_GPIO, BOARD_INITPINS_EX_3_PIN, &EX_3_config);

    gpio_pin_config_t EX_2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC3 (pin 29)  */
    GPIO_PinInit(BOARD_INITPINS_EX_2_GPIO, BOARD_INITPINS_EX_2_PIN, &EX_2_config);

    gpio_pin_config_t EX_8_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC15 (pin 45)  */
    GPIO_PinInit(BOARD_INITPINS_EX_8_GPIO, BOARD_INITPINS_EX_8_PIN, &EX_8_config);

    gpio_pin_config_t EX_7_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC16 (pin 44)  */
    GPIO_PinInit(BOARD_INITPINS_EX_7_GPIO, BOARD_INITPINS_EX_7_PIN, &EX_7_config);

    gpio_pin_config_t EX_6_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC17 (pin 43)  */
    GPIO_PinInit(BOARD_INITPINS_EX_6_GPIO, BOARD_INITPINS_EX_6_PIN, &EX_6_config);

    gpio_pin_config_t MCU_A0_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD0 (pin 4)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_A0_GPIO, BOARD_INITPINS_MCU_A0_PIN, &MCU_A0_config);

    gpio_pin_config_t MCU_A1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD1 (pin 3)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_A1_GPIO, BOARD_INITPINS_MCU_A1_PIN, &MCU_A1_config);

    gpio_pin_config_t MCU_A2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD2 (pin 71)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_A2_GPIO, BOARD_INITPINS_MCU_A2_PIN, &MCU_A2_config);

    gpio_pin_config_t MCU_A3_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD3 (pin 70)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_A3_GPIO, BOARD_INITPINS_MCU_A3_PIN, &MCU_A3_config);

    gpio_pin_config_t MCU_A4_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD4 (pin 69)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_A4_GPIO, BOARD_INITPINS_MCU_A4_PIN, &MCU_A4_config);

    gpio_pin_config_t MCU_A5_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD5 (pin 33)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_A5_GPIO, BOARD_INITPINS_MCU_A5_PIN, &MCU_A5_config);

    gpio_pin_config_t MCU_A6_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD6 (pin 32)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_A6_GPIO, BOARD_INITPINS_MCU_A6_PIN, &MCU_A6_config);

    gpio_pin_config_t MCU_A7_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD7 (pin 31)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_A7_GPIO, BOARD_INITPINS_MCU_A7_PIN, &MCU_A7_config);

    gpio_pin_config_t MCU_A8_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD8 (pin 42)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_A8_GPIO, BOARD_INITPINS_MCU_A8_PIN, &MCU_A8_config);

    gpio_pin_config_t MCU_A9_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD9 (pin 41)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_A9_GPIO, BOARD_INITPINS_MCU_A9_PIN, &MCU_A9_config);

    gpio_pin_config_t MCU_A10_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD10 (pin 36)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_A10_GPIO, BOARD_INITPINS_MCU_A10_PIN, &MCU_A10_config);

    gpio_pin_config_t MCU_A11_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD11 (pin 35)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_A11_GPIO, BOARD_INITPINS_MCU_A11_PIN, &MCU_A11_config);

    gpio_pin_config_t MCU_A12_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD12 (pin 34)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_A12_GPIO, BOARD_INITPINS_MCU_A12_PIN, &MCU_A12_config);

    gpio_pin_config_t MCU_A13_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD13 (pin 25)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_A13_GPIO, BOARD_INITPINS_MCU_A13_PIN, &MCU_A13_config);

    gpio_pin_config_t MCU_A14_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD14 (pin 24)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_A14_GPIO, BOARD_INITPINS_MCU_A14_PIN, &MCU_A14_config);

    gpio_pin_config_t MCU_A15_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD15 (pin 22)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_A15_GPIO, BOARD_INITPINS_MCU_A15_PIN, &MCU_A15_config);

    gpio_pin_config_t MCU_VMA_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD16 (pin 21)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_VMA_GPIO, BOARD_INITPINS_MCU_VMA_PIN, &MCU_VMA_config);

    gpio_pin_config_t MCU_RW_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD17 (pin 20)  */
    GPIO_PinInit(BOARD_INITPINS_MCU_RW_GPIO, BOARD_INITPINS_MCU_RW_PIN, &MCU_RW_config);

    gpio_pin_config_t EX_1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE8 (pin 26)  */
    GPIO_PinInit(BOARD_INITPINS_EX_1_GPIO, BOARD_INITPINS_EX_1_PIN, &EX_1_config);

    /* PORTA0 (pin 79) is configured as PTA0 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_NMI_PORT, BOARD_INITPINS_MCU_NMI_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTA0 (pin 79): Interrupt on falling edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_MCU_NMI_PORT, BOARD_INITPINS_MCU_NMI_PIN, kPORT_InterruptFallingEdge);

    /* PORTA1 (pin 78) is configured as LPUART0_RTS */
    PORT_SetPinMux(BOARD_INITPINS_UART0_RTS_PORT, BOARD_INITPINS_UART0_RTS_PIN, kPORT_MuxAlt6);

    /* PORTA10 (pin 92) is configured as noetm_Trace_SWO */
    PORT_SetPinMux(PORTA, 10U, kPORT_MuxAlt7);

    /* PORTA12 (pin 90) is configured as CAN1_RX */
    PORT_SetPinMux(BOARD_INITPINS_CAN1_RX_PORT, BOARD_INITPINS_CAN1_RX_PIN, kPORT_MuxAlt3);

    /* PORTA13 (pin 89) is configured as CAN1_TX */
    PORT_SetPinMux(BOARD_INITPINS_CAN1_TX_PORT, BOARD_INITPINS_CAN1_TX_PIN, kPORT_MuxAlt3);

    /* PORTA2 (pin 73) is configured as LPUART0_RX */
    PORT_SetPinMux(BOARD_INITPINS_UART0_RX_PORT, BOARD_INITPINS_UART0_RX_PIN, kPORT_MuxAlt6);

    /* PORTA3 (pin 72) is configured as LPUART0_TX */
    PORT_SetPinMux(BOARD_INITPINS_UART0_TX_PORT, BOARD_INITPINS_UART0_TX_PIN, kPORT_MuxAlt6);

    /* PORTA4 (pin 98) is configured as SWD_DIO */
    PORT_SetPinMux(PORTA, 4U, kPORT_MuxAlt7);

    /* PORTA5 (pin 97) is configured as RESET_b */
    PORT_SetPinMux(BOARD_INITPINS_NRESET_PORT, BOARD_INITPINS_NRESET_PIN, kPORT_MuxAlt7);

    /* PORTA6 (pin 58) is configured as PTA6 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_IRQ_PORT, BOARD_INITPINS_MCU_IRQ_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTA6 (pin 58): Interrupt on falling edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_MCU_IRQ_PORT, BOARD_INITPINS_MCU_IRQ_PIN, kPORT_InterruptFallingEdge);

    /* PORTA7 (pin 57) is configured as LPUART1_RTS */
    PORT_SetPinMux(BOARD_INITPINS_UART1_RTS_PORT, BOARD_INITPINS_UART1_RTS_PIN, kPORT_MuxAlt6);

    /* PORTA8 (pin 100) is configured as PTA8 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_E_PORT, BOARD_INITPINS_MCU_E_PIN, kPORT_MuxAsGpio);

    /* PORTA9 (pin 99) is configured as PTA9 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_RESET_PORT, BOARD_INITPINS_MCU_RESET_PIN, kPORT_MuxAsGpio);

    /* PORTB0 (pin 54) is configured as PTB0 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_D0_PORT, BOARD_INITPINS_MCU_D0_PIN, kPORT_MuxAsGpio);

    /* PORTB1 (pin 53) is configured as PTB1 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_D1_PORT, BOARD_INITPINS_MCU_D1_PIN, kPORT_MuxAsGpio);

    /* PORTB14 (pin 66) is configured as PTB14 */
    PORT_SetPinMux(BOARD_INITPINS_LED_1_PORT, BOARD_INITPINS_LED_1_PIN, kPORT_MuxAsGpio);

    /* PORTB15 (pin 65) is configured as PTB15 */
    PORT_SetPinMux(BOARD_INITPINS_LED_2_PORT, BOARD_INITPINS_LED_2_PIN, kPORT_MuxAsGpio);

    /* PORTB16 (pin 64) is configured as PTB16 */
    PORT_SetPinMux(BOARD_INITPINS_LED_3_PORT, BOARD_INITPINS_LED_3_PIN, kPORT_MuxAsGpio);

    /* PORTB17 (pin 63) is configured as PTB17 */
    PORT_SetPinMux(BOARD_INITPINS_LED_4_PORT, BOARD_INITPINS_LED_4_PIN, kPORT_MuxAsGpio);

    /* PORTB2 (pin 48) is configured as PTB2 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_D2_PORT, BOARD_INITPINS_MCU_D2_PIN, kPORT_MuxAsGpio);

    /* PORTB3 (pin 47) is configured as PTB3 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_D3_PORT, BOARD_INITPINS_MCU_D3_PIN, kPORT_MuxAsGpio);

    /* PORTB4 (pin 28) is configured as PTB4 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_D4_PORT, BOARD_INITPINS_MCU_D4_PIN, kPORT_MuxAsGpio);

    /* PORTB5 (pin 27) is configured as PTB5 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_D5_PORT, BOARD_INITPINS_MCU_D5_PIN, kPORT_MuxAsGpio);

    /* PORTB6 (pin 16) is configured as PTB6 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_D6_PORT, BOARD_INITPINS_MCU_D6_PIN, kPORT_MuxAsGpio);

    /* PORTB7 (pin 15) is configured as PTB7 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_D7_PORT, BOARD_INITPINS_MCU_D7_PIN, kPORT_MuxAsGpio);

    /* PORTC0 (pin 40) is configured as FTM0_CH0 */
    PORT_SetPinMux(BOARD_INITPINS_EX_5_PORT, BOARD_INITPINS_EX_5_PIN, kPORT_MuxAlt2);

    /* PORTC1 (pin 39) is configured as PTC1 */
    PORT_SetPinMux(BOARD_INITPINS_EX_4_PORT, BOARD_INITPINS_EX_4_PIN, kPORT_MuxAsGpio);

    /* PORTC15 (pin 45) is configured as PTC15 */
    PORT_SetPinMux(BOARD_INITPINS_EX_8_PORT, BOARD_INITPINS_EX_8_PIN, kPORT_MuxAsGpio);

    /* PORTC16 (pin 44) is configured as PTC16 */
    PORT_SetPinMux(BOARD_INITPINS_EX_7_PORT, BOARD_INITPINS_EX_7_PIN, kPORT_MuxAsGpio);

    /* PORTC17 (pin 43) is configured as PTC17 */
    PORT_SetPinMux(BOARD_INITPINS_EX_6_PORT, BOARD_INITPINS_EX_6_PIN, kPORT_MuxAsGpio);

    /* PORTC2 (pin 30) is configured as PTC2 */
    PORT_SetPinMux(BOARD_INITPINS_EX_3_PORT, BOARD_INITPINS_EX_3_PIN, kPORT_MuxAsGpio);

    /* PORTC3 (pin 29) is configured as PTC3 */
    PORT_SetPinMux(BOARD_INITPINS_EX_2_PORT, BOARD_INITPINS_EX_2_PIN, kPORT_MuxAsGpio);

    /* PORTC4 (pin 96) is configured as SWD_CLK */
    PORT_SetPinMux(PORTC, 4U, kPORT_MuxAlt7);

    /* PORTC6 (pin 81) is configured as LPUART1_RX */
    PORT_SetPinMux(BOARD_INITPINS_UART1_RX_PORT, BOARD_INITPINS_UART1_RX_PIN, kPORT_MuxAlt2);

    /* PORTC7 (pin 80) is configured as LPUART1_TX */
    PORT_SetPinMux(BOARD_INITPINS_UART1_TX_PORT, BOARD_INITPINS_UART1_TX_PIN, kPORT_MuxAlt2);

    /* PORTD0 (pin 4) is configured as PTD0 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_A0_PORT, BOARD_INITPINS_MCU_A0_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[0] = ((PORTD->PCR[0] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: Low drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_LowDriveStrength));

    /* PORTD1 (pin 3) is configured as PTD1 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_A1_PORT, BOARD_INITPINS_MCU_A1_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[1] = ((PORTD->PCR[1] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_DSE_MASK | PORT_PCR_ISF_MASK)))

                     /* Drive Strength Enable: Low drive strength is configured on the corresponding pin, if pin
                      * is configured as a digital output. */
                     | PORT_PCR_DSE(kPORT_LowDriveStrength));

    /* PORTD10 (pin 36) is configured as PTD10 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_A10_PORT, BOARD_INITPINS_MCU_A10_PIN, kPORT_MuxAsGpio);

    /* PORTD11 (pin 35) is configured as PTD11 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_A11_PORT, BOARD_INITPINS_MCU_A11_PIN, kPORT_MuxAsGpio);

    /* PORTD12 (pin 34) is configured as PTD12 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_A12_PORT, BOARD_INITPINS_MCU_A12_PIN, kPORT_MuxAsGpio);

    /* PORTD13 (pin 25) is configured as PTD13 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_A13_PORT, BOARD_INITPINS_MCU_A13_PIN, kPORT_MuxAsGpio);

    /* PORTD14 (pin 24) is configured as PTD14 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_A14_PORT, BOARD_INITPINS_MCU_A14_PIN, kPORT_MuxAsGpio);

    /* PORTD15 (pin 22) is configured as PTD15 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_A15_PORT, BOARD_INITPINS_MCU_A15_PIN, kPORT_MuxAsGpio);

    /* PORTD16 (pin 21) is configured as PTD16 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_VMA_PORT, BOARD_INITPINS_MCU_VMA_PIN, kPORT_MuxAsGpio);

    /* PORTD17 (pin 20) is configured as PTD17 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_RW_PORT, BOARD_INITPINS_MCU_RW_PIN, kPORT_MuxAsGpio);

    /* PORTD2 (pin 71) is configured as PTD2 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_A2_PORT, BOARD_INITPINS_MCU_A2_PIN, kPORT_MuxAsGpio);

    /* PORTD3 (pin 70) is configured as PTD3 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_A3_PORT, BOARD_INITPINS_MCU_A3_PIN, kPORT_MuxAsGpio);

    PORTD->PCR[3] = ((PORTD->PCR[3] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_PS_MASK | PORT_PCR_ISF_MASK)))

                     /* Pull Select: Internal pulldown resistor is enabled on the corresponding pin, if the
                      * corresponding PE field is set. */
                     | PORT_PCR_PS(kPORT_PullDown));

    /* PORTD4 (pin 69) is configured as PTD4 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_A4_PORT, BOARD_INITPINS_MCU_A4_PIN, kPORT_MuxAsGpio);

    /* PORTD5 (pin 33) is configured as PTD5 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_A5_PORT, BOARD_INITPINS_MCU_A5_PIN, kPORT_MuxAsGpio);

    /* PORTD6 (pin 32) is configured as PTD6 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_A6_PORT, BOARD_INITPINS_MCU_A6_PIN, kPORT_MuxAsGpio);

    /* PORTD7 (pin 31) is configured as PTD7 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_A7_PORT, BOARD_INITPINS_MCU_A7_PIN, kPORT_MuxAsGpio);

    /* PORTD8 (pin 42) is configured as PTD8 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_A8_PORT, BOARD_INITPINS_MCU_A8_PIN, kPORT_MuxAsGpio);

    /* PORTD9 (pin 41) is configured as PTD9 */
    PORT_SetPinMux(BOARD_INITPINS_MCU_A9_PORT, BOARD_INITPINS_MCU_A9_PIN, kPORT_MuxAsGpio);

    /* PORTE4 (pin 9) is configured as CAN0_RX */
    PORT_SetPinMux(BOARD_INITPINS_CAN0_RX_PORT, BOARD_INITPINS_CAN0_RX_PIN, kPORT_MuxAlt5);

    /* PORTE5 (pin 8) is configured as CAN0_TX */
    PORT_SetPinMux(BOARD_INITPINS_CAN0_TX_PORT, BOARD_INITPINS_CAN0_TX_PIN, kPORT_MuxAlt5);

    /* PORTE8 (pin 26) is configured as PTE8 */
    PORT_SetPinMux(BOARD_INITPINS_EX_1_PORT, BOARD_INITPINS_EX_1_PIN, kPORT_MuxAsGpio);

    /* PORTE9 (pin 23) is configured as DAC0_OUT */
    PORT_SetPinMux(BOARD_INITPINS_DAC_OUT_PORT, BOARD_INITPINS_DAC_OUT_PIN, kPORT_PinDisabledOrAnalog);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
