/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTA5 (number 97), NRESET
  @{ */
#define BOARD_INITPINS_NRESET_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_NRESET_PIN 5U     /*!<@brief PORTA pin index: 5 */
                                         /* @} */

/*! @name PORTD0 (number 4), MCU_A0
  @{ */
#define BOARD_INITPINS_MCU_A0_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_MCU_A0_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MCU_A0_PIN 0U     /*!<@brief PORTD pin index: 0 */
                                         /* @} */

/*! @name PORTD1 (number 3), MCU_A1
  @{ */
#define BOARD_INITPINS_MCU_A1_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_MCU_A1_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MCU_A1_PIN 1U     /*!<@brief PORTD pin index: 1 */
                                         /* @} */

/*! @name PORTD2 (number 71), MCU_A2
  @{ */
#define BOARD_INITPINS_MCU_A2_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_MCU_A2_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MCU_A2_PIN 2U     /*!<@brief PORTD pin index: 2 */
                                         /* @} */

/*! @name PORTD3 (number 70), MCU_A3
  @{ */
#define BOARD_INITPINS_MCU_A3_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_MCU_A3_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MCU_A3_PIN 3U     /*!<@brief PORTD pin index: 3 */
                                         /* @} */

/*! @name PORTD4 (number 69), MCU_A4
  @{ */
#define BOARD_INITPINS_MCU_A4_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_MCU_A4_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MCU_A4_PIN 4U     /*!<@brief PORTD pin index: 4 */
                                         /* @} */

/*! @name PORTD5 (number 33), MCU_A5
  @{ */
#define BOARD_INITPINS_MCU_A5_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_MCU_A5_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MCU_A5_PIN 5U     /*!<@brief PORTD pin index: 5 */
                                         /* @} */

/*! @name PORTD6 (number 32), MCU_A6
  @{ */
#define BOARD_INITPINS_MCU_A6_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_MCU_A6_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MCU_A6_PIN 6U     /*!<@brief PORTD pin index: 6 */
                                         /* @} */

/*! @name PORTD7 (number 31), MCU_A7
  @{ */
#define BOARD_INITPINS_MCU_A7_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_MCU_A7_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MCU_A7_PIN 7U     /*!<@brief PORTD pin index: 7 */
                                         /* @} */

/*! @name PORTD8 (number 42), MCU_A8
  @{ */
#define BOARD_INITPINS_MCU_A8_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_MCU_A8_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MCU_A8_PIN 8U     /*!<@brief PORTD pin index: 8 */
                                         /* @} */

/*! @name PORTD9 (number 41), MCU_A9
  @{ */
#define BOARD_INITPINS_MCU_A9_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_MCU_A9_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MCU_A9_PIN 9U     /*!<@brief PORTD pin index: 9 */
                                         /* @} */

/*! @name PORTD10 (number 36), MCU_A10
  @{ */
#define BOARD_INITPINS_MCU_A10_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_MCU_A10_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MCU_A10_PIN 10U    /*!<@brief PORTD pin index: 10 */
                                          /* @} */

/*! @name PORTD11 (number 35), MCU_A11
  @{ */
#define BOARD_INITPINS_MCU_A11_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_MCU_A11_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MCU_A11_PIN 11U    /*!<@brief PORTD pin index: 11 */
                                          /* @} */

/*! @name PORTD12 (number 34), MCU_A12
  @{ */
#define BOARD_INITPINS_MCU_A12_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_MCU_A12_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MCU_A12_PIN 12U    /*!<@brief PORTD pin index: 12 */
                                          /* @} */

/*! @name PORTD13 (number 25), MCU_A13
  @{ */
#define BOARD_INITPINS_MCU_A13_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_MCU_A13_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MCU_A13_PIN 13U    /*!<@brief PORTD pin index: 13 */
                                          /* @} */

/*! @name PORTD14 (number 24), MCU_A14
  @{ */
#define BOARD_INITPINS_MCU_A14_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_MCU_A14_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MCU_A14_PIN 14U    /*!<@brief PORTD pin index: 14 */
                                          /* @} */

/*! @name PORTD15 (number 22), MCU_A15
  @{ */
#define BOARD_INITPINS_MCU_A15_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_MCU_A15_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MCU_A15_PIN 15U    /*!<@brief PORTD pin index: 15 */
                                          /* @} */

/*! @name PORTD16 (number 21), MCU_VMA
  @{ */
#define BOARD_INITPINS_MCU_VMA_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_MCU_VMA_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MCU_VMA_PIN 16U    /*!<@brief PORTD pin index: 16 */
                                          /* @} */

/*! @name PORTD17 (number 20), MCU_RW
  @{ */
#define BOARD_INITPINS_MCU_RW_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_MCU_RW_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_MCU_RW_PIN 17U    /*!<@brief PORTD pin index: 17 */
                                         /* @} */

/*! @name PORTA2 (number 73), UART0_RX
  @{ */
#define BOARD_INITPINS_UART0_RX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_UART0_RX_PIN 2U     /*!<@brief PORTA pin index: 2 */
                                           /* @} */

/*! @name PORTA3 (number 72), UART0_TX
  @{ */
#define BOARD_INITPINS_UART0_TX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_UART0_TX_PIN 3U     /*!<@brief PORTA pin index: 3 */
                                           /* @} */

/*! @name PORTA12 (number 90), CAN1_RX
  @{ */
#define BOARD_INITPINS_CAN1_RX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_CAN1_RX_PIN 12U    /*!<@brief PORTA pin index: 12 */
                                          /* @} */

/*! @name PORTA13 (number 89), CAN1_TX
  @{ */
#define BOARD_INITPINS_CAN1_TX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_CAN1_TX_PIN 13U    /*!<@brief PORTA pin index: 13 */
                                          /* @} */

/*! @name PORTC6 (number 81), UART1_RX
  @{ */
#define BOARD_INITPINS_UART1_RX_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_UART1_RX_PIN 6U     /*!<@brief PORTC pin index: 6 */
                                           /* @} */

/*! @name PORTC7 (number 80), UART1_TX
  @{ */
#define BOARD_INITPINS_UART1_TX_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_UART1_TX_PIN 7U     /*!<@brief PORTC pin index: 7 */
                                           /* @} */

/*! @name PORTA1 (number 78), UART0_RTS
  @{ */
#define BOARD_INITPINS_UART0_RTS_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_UART0_RTS_PIN 1U     /*!<@brief PORTA pin index: 1 */
                                            /* @} */

/*! @name PORTA7 (number 57), UART1_RTS
  @{ */
#define BOARD_INITPINS_UART1_RTS_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_UART1_RTS_PIN 7U     /*!<@brief PORTA pin index: 7 */
                                            /* @} */

/*! @name PORTE9 (number 23), DAC_OUT
  @{ */
#define BOARD_INITPINS_DAC_OUT_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_DAC_OUT_PIN 9U     /*!<@brief PORTE pin index: 9 */
                                          /* @} */

/*! @name PORTE4 (number 9), CAN0_RX
  @{ */
#define BOARD_INITPINS_CAN0_RX_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_CAN0_RX_PIN 4U     /*!<@brief PORTE pin index: 4 */
                                          /* @} */

/*! @name PORTE5 (number 8), CAN0_TX
  @{ */
#define BOARD_INITPINS_CAN0_TX_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_CAN0_TX_PIN 5U     /*!<@brief PORTE pin index: 5 */
                                          /* @} */

/*! @name PORTB0 (number 54), MCU_D0
  @{ */
#define BOARD_INITPINS_MCU_D0_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_MCU_D0_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_MCU_D0_PIN 0U     /*!<@brief PORTB pin index: 0 */
                                         /* @} */

/*! @name PORTB1 (number 53), MCU_D1
  @{ */
#define BOARD_INITPINS_MCU_D1_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_MCU_D1_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_MCU_D1_PIN 1U     /*!<@brief PORTB pin index: 1 */
                                         /* @} */

/*! @name PORTB2 (number 48), MCU_D2
  @{ */
#define BOARD_INITPINS_MCU_D2_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_MCU_D2_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_MCU_D2_PIN 2U     /*!<@brief PORTB pin index: 2 */
                                         /* @} */

/*! @name PORTB3 (number 47), MCU_D3
  @{ */
#define BOARD_INITPINS_MCU_D3_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_MCU_D3_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_MCU_D3_PIN 3U     /*!<@brief PORTB pin index: 3 */
                                         /* @} */

/*! @name PORTB4 (number 28), MCU_D4
  @{ */
#define BOARD_INITPINS_MCU_D4_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_MCU_D4_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_MCU_D4_PIN 4U     /*!<@brief PORTB pin index: 4 */
                                         /* @} */

/*! @name PORTB5 (number 27), MCU_D5
  @{ */
#define BOARD_INITPINS_MCU_D5_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_MCU_D5_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_MCU_D5_PIN 5U     /*!<@brief PORTB pin index: 5 */
                                         /* @} */

/*! @name PORTB6 (number 16), MCU_D6
  @{ */
#define BOARD_INITPINS_MCU_D6_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_MCU_D6_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_MCU_D6_PIN 6U     /*!<@brief PORTB pin index: 6 */
                                         /* @} */

/*! @name PORTB7 (number 15), MCU_D7
  @{ */
#define BOARD_INITPINS_MCU_D7_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_MCU_D7_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_MCU_D7_PIN 7U     /*!<@brief PORTB pin index: 7 */
                                         /* @} */

/*! @name PORTA0 (number 79), MCU_NMI
  @{ */
#define BOARD_INITPINS_MCU_NMI_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_MCU_NMI_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_MCU_NMI_PIN 0U     /*!<@brief PORTA pin index: 0 */
                                          /* @} */

/*! @name PORTA6 (number 58), MCU_IRQ
  @{ */
#define BOARD_INITPINS_MCU_IRQ_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_MCU_IRQ_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_MCU_IRQ_PIN 6U     /*!<@brief PORTA pin index: 6 */
                                          /* @} */

/*! @name PORTA9 (number 99), MCU_RESET
  @{ */
#define BOARD_INITPINS_MCU_RESET_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_MCU_RESET_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_MCU_RESET_PIN 9U     /*!<@brief PORTA pin index: 9 */
                                            /* @} */

/*! @name PORTB14 (number 66), LED_1
  @{ */
#define BOARD_INITPINS_LED_1_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LED_1_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LED_1_PIN 14U    /*!<@brief PORTB pin index: 14 */
                                        /* @} */

/*! @name PORTB15 (number 65), LED_2
  @{ */
#define BOARD_INITPINS_LED_2_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LED_2_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LED_2_PIN 15U    /*!<@brief PORTB pin index: 15 */
                                        /* @} */

/*! @name PORTB17 (number 63), LED_4
  @{ */
#define BOARD_INITPINS_LED_4_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LED_4_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LED_4_PIN 17U    /*!<@brief PORTB pin index: 17 */
                                        /* @} */

/*! @name PORTB16 (number 64), LED_3
  @{ */
#define BOARD_INITPINS_LED_3_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LED_3_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LED_3_PIN 16U    /*!<@brief PORTB pin index: 16 */
                                        /* @} */

/*! @name PORTC1 (number 39), EX_4
  @{ */
#define BOARD_INITPINS_EX_4_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_EX_4_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_EX_4_PIN 1U     /*!<@brief PORTC pin index: 1 */
                                       /* @} */

/*! @name PORTC2 (number 30), EX_3
  @{ */
#define BOARD_INITPINS_EX_3_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_EX_3_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_EX_3_PIN 2U     /*!<@brief PORTC pin index: 2 */
                                       /* @} */

/*! @name PORTC3 (number 29), EX_2
  @{ */
#define BOARD_INITPINS_EX_2_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_EX_2_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_EX_2_PIN 3U     /*!<@brief PORTC pin index: 3 */
                                       /* @} */

/*! @name PORTC15 (number 45), EX_8
  @{ */
#define BOARD_INITPINS_EX_8_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_EX_8_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_EX_8_PIN 15U    /*!<@brief PORTC pin index: 15 */
                                       /* @} */

/*! @name PORTC16 (number 44), EX_7
  @{ */
#define BOARD_INITPINS_EX_7_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_EX_7_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_EX_7_PIN 16U    /*!<@brief PORTC pin index: 16 */
                                       /* @} */

/*! @name PORTC17 (number 43), EX_6
  @{ */
#define BOARD_INITPINS_EX_6_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_EX_6_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_EX_6_PIN 17U    /*!<@brief PORTC pin index: 17 */
                                       /* @} */

/*! @name PORTE8 (number 26), EX_1
  @{ */
#define BOARD_INITPINS_EX_1_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_EX_1_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_EX_1_PIN 8U     /*!<@brief PORTE pin index: 8 */
                                       /* @} */

/*! @name PORTA8 (number 100), MCU_E
  @{ */
#define BOARD_INITPINS_MCU_E_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_MCU_E_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_MCU_E_PIN 8U     /*!<@brief PORTA pin index: 8 */
                                        /* @} */

/*! @name PORTC0 (number 40), EX_5_E_CLK_OUT
  @{ */
#define BOARD_INITPINS_EX_5_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_EX_5_PIN 0U     /*!<@brief PORTC pin index: 0 */
                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
